update: add secret check before publishing to PyPI

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -29,10 +29,22 @@ jobs:
           --publish-url https://pypi.pkg.github.com \
           --username ${{ github.repository_owner }} \
           --password ${{ secrets.GITHUB_TOKEN }}
+      - name: check secret
+        id: check
+        env:
+          TARGET_SECRET: ${{ secrets.PYPI_API_TOKEN }}
+        run: |
+          if [ -z "$TARGET_SECRET" ]; then
+            echo "secret_missing=true" >> $GITHUB_OUTPUT
+            exit 1
+          else
+            echo "secret_missing=false" >> $GITHUB_OUTPUT
+          fi
       - name: upload to pypi
         run: uv publish \
           --username __token__ \
           --password ${{ secrets.PYPI_API_TOKEN }}
+        if: steps.check.outputs.secret_missing == 'false' # when secret is missing, skip this step
   publish-github:
     needs: build
     runs-on: ubuntu-latest
